services:
  jenkins:
    restart: unless-stopped
    image: chinmaymjog/jenkins-ansible:latest
    container_name: jenkins-ansible
    volumes:
      - ./jenkins-home:/var/lib/jenkins:rw
      - ./ansible:/etc/ansible:rw
      - ./site-data:/site-data:rw
      - /backup:/backup:rw
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 8081:8080
    networks:
      - shared

networks:
  shared:
    external: true
