---
- name: Backup all databases
  hosts: localhost
  become: true
  vars_files:
    - var_files/web_vars.yml
    - var_files/database_vars.yml

  tasks:
    - name: Set environment-specific database variables
      set_fact:
        db_host: "{{ lookup('vars', web_environment).db_host }}"
        db_port: "{{ lookup('vars', web_environment).db_port | default(3306) }}"
        db_user: "{{ lookup('vars', web_environment).db_user }}"
        db_pass: "{{ lookup('vars', web_environment).db_pass }}"

    - name: find db
      shell: mysql -h {{ db_host }} -u {{ db_user }} -p"{{ db_pass }}" -e "SHOW DATABASES;"|grep -Ev "(Database|information_schema|performance_schema|sys|mysql)"
      register: my_dbs

    - name: print
      debug:
        msg: "{{my_dbs.stdout_lines}}"

    - name: Take Backup
      shell: |
        mysqldump --force --opt --skip-lock-tables -h {{ db_host }} -u {{ db_user }} -p"{{ db_pass }}" --databases {{ item }} | gzip > {{ BACKUP_PATH }}/{{ web_environment }}/database_backup/{{ item }}_{{ ansible_date_time.date | regex_replace('-', '') }}.sql.gz
      loop: "{{ my_dbs.stdout_lines }}"
      args:
        executable: /bin/bash
