---
- name: Backup Site Configuration
  hosts: "{{ web_environment }}"
  become: true
  vars_files:
    - var_files/web_vars.yml

  tasks:
    - name: Take Backup
      shell: >
        find -L {{ DOC_ROOT }} -maxdepth 4 -type f \( -name ".env" -o -name ".htaccess" -o -name "wp-config.php" \) -exec tar -cvf "{{ BACKUP_PATH }}/{{ web_environment }}/site_config_backup/siteconfig_{{ ansible_hostname }}_{{ ansible_date_time.date | regex_replace('-', '') }}.tar" {} +
